name: joborder

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    needs: [job2]
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job1"
      - name: check flag
        env:
          JOB2_FLAG: ${{ needs.job2.outputs.succ_flag }}
        run: |
          if [ $JOB2_FLAG == "1" ]
          then
            exit 0
          else
            exit 1
          fi       
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: [job3]
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job2"
      - name: check flag
        env:
          JOB3_FLAG: ${{ needs.job3.outputs.succ_flag }}
        run: |
          if [ $JOB3_FLAG == "1" ]
          then
            exit 0
          else
            exit 1
          fi       
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"
      

  job3:
    runs-on: ubuntu-latest
    needs: []
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job3"
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job4"
      - name: check flag
        env:
          JOB2_FLAG: ${{ needs.job2.outputs.succ_flag }}
          JOB3_FLAG: ${{ needs.job3.outputs.succ_flag }}
        run: |
          if [ $JOB2_FLAG == "1" && $JOB3_FLAG == "1" ]
          then
            exit 0
          else
            exit 1
          fi    
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"

  job5:
    runs-on: ubuntu-latest
    needs: [job2, job4]
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job5"
      - name: check flag
        env:
          JOB2_FLAG: ${{ needs.job2.outputs.succ_flag }}
          JOB4_FLAG: ${{ needs.job4.outputs.succ_flag }}
        run: |
          if [ $JOB2_FLAG == "1" && $JOB4_FLAG == "1" ]
          then
            exit 0
          else
            exit 1
          fi    
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"

  job6:
    runs-on: ubuntu-latest
    needs: [job1, job2, job4, job5]
    outputs:
      succ_flag: ${{ steps.flagstep.outputs.flag }}
    steps:
      - run: echo "job6"
      - name: check flag
        env:
          JOB1_FLAG: ${{ needs.job1.outputs.succ_flag }}
          JOB2_FLAG: ${{ needs.job2.outputs.succ_flag }}
          JOB4_FLAG: ${{ needs.job4.outputs.succ_flag }}
          JOB5_FLAG: ${{ needs.job5.outputs.succ_flag }}
        run: |
          if [ $JOB1_FLAG == "1" && $JOB2_FLAG == "1" && $JOB4_FLAG == "1" && $JOB5_FLAG == "1" ]
          then
            exit 0
          else
            exit 1
          fi    
      - name: set flag
        id: flagstep
        run: echo "flag=1" >> "$GITHUB_OUTPUT"
